### ISSUE TITLE
Please update to the latest version of LastPass.

### ISSUE THREAD

**Issue by MacabreMilkman** [dmaasland/lastpass-authenticator-export#8]
The script runs, accepts the user flag and asks for the password, then prints this:

`Login failed!`
`<response><error server="lastpass.eu" message="Please update to the latest version of LastPass." /></response>`

**Comment by altano** [comment]
FWIW disabling 2fa in LastPass didn't help me either. I still got this error message.

**Comment by dmaasland** [comment]
Hmm I can't find any way of reproducing this. However, I've just pushed a commit that (I hope) fixes another issue. Could you give this version a try?

**Comment by MacabreMilkman** [comment]
Thank you for trying.  Still the same error though I'm afraid.  I ended up just re-configuring all my 2FAs manually instead.
